In [1]:

import numpy as np
import pandas as pd

###`Q-1:` Write a program to create an empty series.

In [4]:
# code here
empty = np.empty(5)
emp = pd.Series(empty)
print(emp)

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
dtype: float64

###`Q-2:` Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [5]:
# code here
data = np.arange(15)
df = pd.Series(data)

print(df + 10)
print(df - 9)
print(df * 2)
print(df /2)

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
11    21
12    22
13    23
14    24
dtype: int64
0    -9
1    -8
2    -7
3    -6
4    -5
5    -4
6    -3
7    -2
8    -1
9     0
10    1
11    2
12    3
13    4
14    5
dtype: int64
0      0
1      2
2      4
3      6
4      8
5     10
6     12
7     14
8     16
9     18
10    20
11    22
12    24
13    26
14    28
dtype: int64
0     0.0
1     0.5
2     1.0
3     1.5
4     2.0
5     2.5
6     3.0
7     3.5
8     4.0
9     4.5
10    5.0
11    5.5
12    6.0
13    6.5
14    7.0
dtype: float64

###`Q-3` Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [6]:
# code here
series1 = pd.Series([2,4,6,8,10])
series2 = pd.Series([1,3,5,7,9])

print( series1 == series2)

0    False
1    False
2    False
3    False
4    False
dtype: bool

###`Q-5.`Write a function to change the data type of given a column or a Series. Function takes series and data type as input, returns the converted series.
```
series = pd.Series([1,2,'Python', 2.0, True, 100])
change to float type data
```
Note: Read about pd.to_numeric()

In [8]:
# code here
def change_data(series):
    
    return pd.to_numeric(series,errors= 'coerce')

series = pd.Series([1,2,'Python', 2.0, True, 100])
change_data(series)

0      1.0
1      2.0
2      NaN
3      2.0
4      1.0
5    100.0
dtype: float64

Download data - https://drive.google.com/file/d/1LRhXwbEodeWXtzPhJCX0X9Lf_BECzvqb/view?usp=share_link
All Batsman runs series in IPL 2008 to 2022.

Below questions are based on this data.

###`Q-6` Find top 10 most run getter from the series.

In [15]:
# code here
df = pd.read_csv('batsman_runs_series.csv')
df

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [17]:
df.sort_values('batsman_run', ascending=False).head(10)

             batter  batsman_run
569         V Kohli         6634
462        S Dhawan         6244
130       DA Warner         5883
430       RG Sharma         5881
493        SK Raina         5536
27   AB de Villiers         5181
108        CH Gayle         4997
339        MS Dhoni         4978
452      RV Uthappa         4954
256      KD Karthik         4377

###`Q-7` No of players having runs above 3000

In [20]:
# code here
df[df['batsman_run']>3000]

             batter  batsman_run
27   AB de Villiers         5181
46        AM Rahane         4074
60        AT Rayudu         4190
108        CH Gayle         4997
130       DA Warner         5883
169    F du Plessis         3403
174       G Gambhir         4217
251      KA Pollard         3437
256      KD Karthik         4377
263        KL Rahul         3895
328       MK Pandey         3657
339        MS Dhoni         4978
430       RG Sharma         5881
452      RV Uthappa         4954
462        S Dhawan         6244
493        SK Raina         5536
511       SR Watson         3880
519       SV Samson         3526
569         V Kohli         6634
597       YK Pathan         3222

###`Q-8` No of players having runs above mean value?

In [25]:
# code here
df_mean = df['batsman_run'].mean()
print(df_mean)
df[df['batsman_run'] > df_mean]

464.42809917355373

              batter  batsman_run
15         A Symonds          974
27    AB de Villiers         5181
29      AC Gilchrist         2069
34        AD Mathews          724
36        AD Russell         2039
..               ...          ...
587          WP Saha         2427
594  Y Venugopal Rao          985
596      YBK Jaiswal          547
597        YK Pathan         3222
603     Yuvraj Singh         2754

[128 rows x 2 columns]

Download data - https://drive.google.com/file/d/1QZuZ5bypUInfVvarHACLAi8tXXHvb8xd/view?usp=share_link

file name - items.csv

###`Q-9`
    i. Read `items.csv` making `item_name` as index.
    ii. Show no of nan values
    ii. Item price is given in $, so convert it to rupees without currency symbol.
    iii. Make data type of newly made series as float.
    iv. Fill nan with mean of the series


How csv file looks

```
item_name	item_price
Chips and Fresh Tomato Salsa	$2.39
Izze	$3.39
Nantucket Nectar	$3.39
Chips and Tomatillo-Green Chili Salsa	$2.39
Chicken Bowl	$16.98

```

In [ ]:
# code here

###`Q-10`:
    i. Find mean price
    ii. Find 30th and 6th percentile value
    iii. Plot Histogram on price with bin size 50
    iv. No of items price lies between [1000 to 2000]

In [ ]:
# code here